# Use an official Python runtime as a parent image
FROM python:3.9

# Set the working directory to /app
WORKDIR /app

# Copy folder content into the container at /app
COPY . /app/

# Create output directories
RUN mkdir -p /app/output/

# Install required packages
RUN pip install --no-cache-dir -r requirements.txt

# Run data_wrangling.py, classification_model.py, and save predictions when the container launches
CMD ["sh", "-c", "python data_wrangling.py && python classification_model.py"]